#! /bin/bash

set -e

case "$1" in
    configure)
        update-rc.d datadog-agent defaults
        adduser --system dd-agent --disabled-login --shell /bin/false --no-create-home --quiet
        usermod -d /usr/share/datadog/agent dd-agent
        chown root:root /etc/init.d/datadog-agent
        chown -R dd-agent:root /etc/dd-agent
        chown -R dd-agent:root /var/log/datadog
        chown -R root:root /usr/share/datadog
        chown -h root:root /usr/bin/dogstatsd
        chown -h root:root /usr/bin/dd-agent
        chown -h root:root /usr/bin/dd-forwarder
        # Install the virtual env and the dependencies
        python /usr/share/datadog/agent/libs/virtualenv.py --system-site-packages --no-pip --no-setuptools /usr/share/datadog/agent/venv
        /usr/share/datadog/agent/venv/python /usr/share/datadog/agent/libs/ez_setup.py
        /usr/share/datadog/agent/venv/python /usr/share/datadog/agent/libs/get-pip.py
        /usr/share/datadog/agent/venv/python /usr/share/datadog/agent/pip install tornado==3.1.1
        /usr/share/datadog/agent/venv/python /usr/share/datadog/agent/pip install supervisor==3.0

        set +e

        if which invoke-rc.d >/dev/null 2>&1; then
            invoke-rc.d datadog-agent restart
        else
            /etc/init.d/datadog-agent restart
        fi

        RETVAL=$?
        if [ $RETVAL -ne 0 ]; then
          if [ $RETVAL -eq 3 ]; then
            # No datadog.conf file is present. The user is probably following
            # the step-by-step instructions and will add the config file next.
            exit 0
          else
            exit $?
          fi
        fi
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
    ;;
esac

#DEBHELPER#

exit 0
